# Generated by Django 4.1.1 on 2022-10-06 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bank", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tranaction",
            name="t_facc",
        ),
        migrations.RemoveField(
            model_name="tranaction",
            name="t_tacc",
        ),
        migrations.RemoveField(
            model_name="user_acc",
            name="a_id",
        ),
        migrations.RemoveField(
            model_name="user_acc",
            name="u_id",
        ),
        migrations.DeleteModel(
            name="acc_cards",
        ),
        migrations.DeleteModel(
            name="Account",
        ),
        migrations.DeleteModel(
            name="Cards",
        ),
        migrations.DeleteModel(
            name="Tranaction",
        ),
        migrations.DeleteModel(
            name="User",
        ),
        migrations.DeleteModel(
            name="user_acc",
        ),
    ]
