# Generated by Django 4.1.1 on 2022-10-06 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bank", "0004_alter_account_acc_opendate"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cards",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("c_id", models.CharField(max_length=20)),
                ("c_type", models.CharField(max_length=10)),
                ("c_pin", models.IntegerField()),
                ("c_limit", models.IntegerField()),
                ("c_doc", models.DateTimeField(auto_now_add=True)),
                (
                    "acc_c",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="bank.account"
                    ),
                ),
            ],
        ),
    ]
