# Generated by Django 4.1.1 on 2022-10-06 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bank", "0005_cards"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Cards",
            new_name="Card",
        ),
    ]
