# Generated by Django 4.1.1 on 2022-10-06 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bank", "0006_rename_cards_card"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tranaction",
            fields=[
                ("t_id", models.AutoField(primary_key=True, serialize=False)),
                ("t_ammount", models.FloatField()),
                ("t_doc", models.DateTimeField(auto_now_add=True)),
                ("t_status", models.CharField(max_length=20)),
                ("t_revert_req", models.BooleanField()),
                (
                    "t_facc",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="from_account",
                        to="bank.account",
                    ),
                ),
                (
                    "t_tacc",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="to_account",
                        to="bank.account",
                    ),
                ),
            ],
        ),
    ]
