# Generated by Django 4.1.1 on 2022-10-06 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bank", "0007_tranaction"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Tranaction",
            new_name="Transaction",
        ),
    ]
