# Generated by Django 4.1.1 on 2022-10-06 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bank", "0008_rename_tranaction_transaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="t_status",
            field=models.BooleanField(),
        ),
    ]
