# Generated by Django 4.1.1 on 2022-10-06 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bank", "0009_alter_transaction_t_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="id",
        ),
        migrations.RemoveField(
            model_name="card",
            name="id",
        ),
        migrations.AlterField(
            model_name="account",
            name="acc_no",
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="card",
            name="c_id",
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
