# Generated by Django 4.1.1 on 2022-10-09 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bank", "0010_remove_account_id_remove_card_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="acc_c",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
